version: '3.3'

services:
    ftp_server:
        build: ./docker/ftp
        image: ubuntu-ftp-server
        container_name: ftp_server
        environment:
            - FTP_USER=user_ftp
            - FTP_PASS=pwd@!234
        ports:
            - "20:20"
            - "21:21"
            - "47400-47470:47400-47470"
        networks:
            - backend

    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=mlflow_db
            - MYSQL_USER=mlflow_db_user
            - MYSQL_PASSWORD=mlflow_db_user
            - MYSQL_ROOT_PASSWORD=mlflow_db_root
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./docker/mlflow
        image: mlflow_server
        container_name: mlflow_server
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - dbmodel:/opt/mlflow
        depends_on:
            - db
            - ftp_server

networks:
    backend:
        driver: bridge

volumes:
    dbmodel:
    dbdata: