version: '3.3'

services:
    ftp_server:
        build: ./ftp
        image: alpine-ftp-server
        container_name: ftp_server
        environment:
            - USERS=ftp_user|pwd@!234
            - ADDRESS=ftp.mlflow
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        networks:
            - frontend
            - backend

    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=mlflow_db
            - MYSQL_USER=mlflow_db_user
            - MYSQL_PASSWORD=mlflow_db_user
            - MYSQL_ROOT_PASSWORD=mlflow_db_root
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        volumes:
            - dbmodel:/opt/mlflow
        depends_on:
            - db
            - ftp_server

    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - web

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbmodel:
    dbdata: